apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    tier: database
    component: mysql
spec: 
  replicas: 2
  serviceName: mysql-headless # head leass service
  minReadySeconds: 10
  
  selector:
    matchLabels:  
      tier: database
      component: mysql
   # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-sc 
      resources:
        requests:
          storage: 2Gi

  template:
    metadata:
      labels:
        tier: database
        component: mysql
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1b
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: naveenrajoli/2025mysql:1.0.0
        ports:
        - containerPort: 3306

        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql

        resources:
          limits: # hard limit
            cpu: "180m"
            memory: "200Mi"
          requests:
            cpu: "120m"
            memory: "150Mi"