apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: expense
  labels:
    tier: frontend
    component: web
spec:
  selector:
    tier: frontend
    component: web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000